import type { Metadata } from "next";
import type { ReactNode } from "react";
import {
  ExternalLink,
  ShieldCheck,
} from "lucide-react";

import reportData from "../../research/cell-pipeline/docs/validation_report.json";
import ZoomableFigure from "../components/ZoomableFigure";

/*
  The report content is generated by the cell pipeline
  (research/cell-pipeline/src/build_validation_report.py) and imported
  as-is, so this page never drifts from the published numbers.
*/

type Block =
  | { type: "h1" | "h2" | "p"; text: string }
  | { type: "table"; head: string[]; rows: string[][] }
  | { type: "ul"; items: string[] };

type ValidationReport = {
  release: string;
  generated: string;
  blocks: Block[];
};

const report = reportData as ValidationReport;

export const metadata: Metadata = {
  title: "Validation",
  description:
    "Validation report for the BioLayers AI cell pipeline: segmentation, tracking, phenotype rules and literature linking, measured on public benchmarks.",
};

const SOURCE_URL =
  "https://github.com/azizbekgayratov65-sys/biolayers-ai/tree/main/research/cell-pipeline";

// Evidence levels must never look equivalent (handoff display rule 1).
const LEVEL_STYLES: Record<string, string> = {
  observed_directly_in_image:
    "border-emerald-400/30 bg-emerald-400/10 text-emerald-200",
  supported_by_literature: "border-sky-400/30 bg-sky-400/10 text-sky-200",
  inferred_by_model: "border-amber-400/30 bg-amber-400/10 text-amber-200",
};

// Renders the **bold** and `code` markup used in the report text.
function inline(text: string): ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <strong key={i} className="font-semibold text-white">
          {part.slice(2, -2)}
        </strong>
      );
    }
    if (part.startsWith("`") && part.endsWith("`")) {
      const code = part.slice(1, -1);
      const levelStyle = LEVEL_STYLES[code];
      return (
        <code
          key={i}
          className={`rounded-md border px-1.5 py-0.5 font-mono text-[0.85em] ${
            levelStyle ?? "border-teal-100/10 bg-white/[0.04] text-teal-100"
          }`}
        >
          {code}
        </code>
      );
    }
    return part;
  });
}

function findTable(column: string) {
  const block = report.blocks.find(
    (b) => b.type === "table" && b.head.includes(column),
  );
  return block?.type === "table" ? block : undefined;
}

function cell(table: ReturnType<typeof findTable>, column: string, row = 0) {
  if (!table) return undefined;
  return table.rows[row]?.[table.head.indexOf(column)];
}

const nuclei = findTable("F1");
const tracking = findTable("SEG (mean Jaccard)");

const HIGHLIGHTS = [
  { label: "Nuclei F1", value: cell(nuclei, "F1"), note: "BBBC039, 200 images" },
  { label: "Precision", value: cell(nuclei, "Precision"), note: "Objects at IoU ≥ 0.5" },
  { label: "Recall", value: cell(nuclei, "Recall"), note: "Objects at IoU ≥ 0.5" },
  {
    label: "Link accuracy",
    value: cell(tracking, "Link accuracy"),
    note: "U373 time-lapse, seq 01",
  },
].filter((h) => h.value);

const titleBlock = report.blocks.find((b) => b.type === "h1");
const introBlock = report.blocks.find((b) => b.type === "p");
const bodyBlocks = report.blocks.filter(
  (b) => b !== titleBlock && b !== introBlock,
);

function renderBlock(block: Block, i: number) {
  switch (block.type) {
    case "h1":
    case "h2":
      return (
        <h2
          key={i}
          className="mt-12 border-b border-teal-100/[0.08] pb-3 text-xl font-serif font-bold tracking-tight text-white sm:text-2xl"
        >
          {block.text}
        </h2>
      );
    case "p":
      return (
        <p key={i} className="mt-4 text-sm leading-7 text-slate-300">
          {inline(block.text)}
        </p>
      );
    case "ul":
      return (
        <ul key={i} className="mt-4 space-y-2.5">
          {block.items.map((item, j) => (
            <li
              key={j}
              className="flex gap-3 text-sm leading-6 text-slate-300"
            >
              <span className="mt-2.5 h-1 w-1 shrink-0 rounded-full bg-teal-300" />
              <span>{inline(item)}</span>
            </li>
          ))}
        </ul>
      );
    case "table":
      return (
        <div
          key={i}
          className="mt-5 overflow-x-auto rounded-2xl border border-teal-100/10 bg-white/[0.02]"
        >
          <table className="w-full border-collapse text-left text-xs sm:text-sm">
            <thead>
              <tr className="border-b border-teal-100/10 bg-white/[0.03]">
                {block.head.map((h) => (
                  <th
                    key={h}
                    className="px-4 py-3 font-mono text-[10px] font-semibold uppercase tracking-wider text-teal-200"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {block.rows.map((row, r) => (
                <tr
                  key={r}
                  className="border-b border-teal-100/[0.06] last:border-0"
                >
                  {row.map((value, c) => (
                    <td
                      key={c}
                      className="px-4 py-3 align-top leading-6 text-slate-300"
                    >
                      {inline(value)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
  }
}

export default function ValidationPage() {
  return (
    <div className="relative isolate overflow-hidden bg-transparent px-6 pt-28 pb-16 sm:px-10 sm:pt-32 lg:px-16 lg:pt-36">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute left-1/2 top-40 -z-20 h-[550px] w-[950px] -translate-x-1/2 rounded-full bg-teal-400/[0.045] blur-[170px]"
      />

      <div className="mx-auto w-full max-w-5xl">
        {/* HEADER */}
        <div className="text-center animate-fade-up">
          <div className="inline-flex items-center gap-2 rounded-full border border-emerald-500/25 bg-emerald-500/10 px-4 py-1.5 backdrop-blur-xl">
            <ShieldCheck className="h-3.5 w-3.5 text-emerald-400" />
            <span className="font-mono text-[10px] font-bold uppercase tracking-widest text-emerald-300">
              Release {report.release} · {report.generated}
            </span>
          </div>

          <h1 className="mt-4 text-3xl font-serif font-bold leading-tight tracking-tight text-white sm:text-4xl lg:text-5xl">
            Cell Pipeline{" "}
            <span className="bg-gradient-to-r from-emerald-200 via-teal-200 to-sky-300 bg-clip-text text-transparent">
              Validation Report
            </span>
          </h1>

          {introBlock?.type === "p" && (
            <p className="mx-auto mt-3 max-w-2xl text-xs leading-relaxed text-slate-300 sm:text-sm">
              {inline(introBlock.text)}
            </p>
          )}
        </div>

        {/* HEADLINE METRICS */}
        <div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-4">
          {HIGHLIGHTS.map((h) => (
            <div
              key={h.label}
              className="rounded-[22px] border border-teal-200/20 bg-gradient-to-b from-[#0a121d]/90 to-[#04080e]/95 p-5 shadow-[0_20px_60px_rgba(0,0,0,0.35)] backdrop-blur-2xl animate-fade-up delay-75"
            >
              <p className="font-mono text-[9px] font-bold uppercase tracking-widest text-teal-300">
                {h.label}
              </p>
              <p className="mt-2 font-mono text-3xl font-semibold tabular-nums text-white">
                {h.value}
              </p>
              <p className="mt-1 text-[11px] text-slate-400">{h.note}</p>
            </div>
          ))}
        </div>

        {/* SAMPLE OUTPUT */}
        <div className="mt-6 grid gap-6 lg:grid-cols-2">
          <ZoomableFigure
            idPrefix="bbbc"
            src="/validation/bbbc039_image.png"
            alt="BBBC039 fluorescence image of U2OS nuclei"
            width={696}
            height={520}
            overlaySrc="/validation/bbbc039_overlay_transparent.png"
            overlayAlt="Segmentation outlines coloured by phenotype label"
            caption="One BBBC039 test image with the pipeline's transparent overlay. Green: no flag. Orange: abnormal morphology. Red: apoptotic/dead. Grey: cut by the image edge."
          />

          <ZoomableFigure
            idPrefix="u373"
            src="/validation/u373_flagship.png"
            alt="Image to cell to phenotype to biological entity chain for flagship cell U373-02-T7"
            width={1950}
            height={1118}
            caption="Flagship cell U373-02-T7: image, cell, phenotype, then the literature link. The link is a hypothesis for this cell, not an observation."
          />
        </div>

        {/* FULL REPORT */}
        <article className="mt-6 rounded-[26px] border border-teal-200/20 bg-gradient-to-b from-[#0a121d]/90 via-[#070c14]/85 to-[#04080e]/95 p-6 shadow-[0_20px_60px_rgba(0,0,0,0.45)] backdrop-blur-2xl sm:p-10">
          {bodyBlocks.map(renderBlock)}

          <div className="mt-12 flex flex-wrap items-center justify-between gap-3 border-t border-teal-100/[0.08] pt-5">
            <a
              href={SOURCE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="group/btn inline-flex items-center gap-2 text-xs font-bold text-teal-300 transition hover:text-teal-100"
            >
              <span>Pipeline source and raw outputs</span>
              <ExternalLink className="h-3.5 w-3.5 transition-transform group-hover/btn:translate-x-0.5" />
            </a>
            <span className="font-mono text-[9px] text-slate-500">
              research/cell-pipeline
            </span>
          </div>
        </article>
      </div>
    </div>
  );
}
